config/routes.rb
Rails.application.routes.draw do
  get 'about/index'

  get 'register/index'
  get 'login/index'
  get 'welcome/index'

  devise_for :commerces, path: 'commerces', controllers: { sessions: 'commerces/sessions', registrations: 'commerces/registrations' } 
  devise_for :users, path: 'users', controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :commerces do 
  	resources :products
    resources :reviews
  end

  resources :products

  root "welcome#index"

  get 'commerces/:id' => 'commerces#show'

  get 'auth/:provider/callback' => 'sessions#create'
  get 'auth/failure' => redirect('/')
  delete 'signout' => 'sessions#destroy'
end

app/models/commerce.rb
class Commerce < ApplicationRecord
  extend FriendlyId
  friendly_id :commerce_name, use: :slugged
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :commerce_name, :address, :phone_number, :logo, presence: true
  has_many :products
  has_many :reviews

  	has_attached_file :logo, styles: { large: "600x600>" }, 
		:path => ":rails_root/public/system/:logo/:id/:style/:filename",
    	:url => "/system/:logo/:id/:style/:filename"
  	validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/

  	has_attached_file :image, styles: { large: "600x600>" }, 
		:path => ":rails_root/public/system/:image/:id/:style/:filename",
    	:url => "/system/:image/:id/:style/:filename"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

    geocoded_by :address
    after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }  
end

app/controllers/commerces/confirmations_controller.rb
# frozen_string_literal: true

class Commerces::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/commerces/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Commerces::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/commerces/passwords_controller.rb
# frozen_string_literal: true

class Commerces::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/commerces/registrations_controller.rb
# frozen_string_literal: true

class Commerces::RegistrationsController < Devise::RegistrationsController

  def show
    @commerce = Commerce.find(params[:commerce_id])
  end

  def update
  @commerce = Commerce.find(current_commerce.id)
    respond_to do |format|
      if @commerce.update(commerce_params)
        format.html { redirect_to root_url }
        format.json { render :show, status: :ok, location: @commerce }
      else
        format.html { render :edit }
        format.json { render json: @commerce.errors, status: :unprocessable_entity }
      end
    end
  end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
 


  private
    def sign_up_params
      params.require(:commerce).permit(:first_name, :last_name, :commerce_name, :email, :password, :password_confirmation, :address, :phone_number, :latitude, :longitude, :register_commerce, :logo, :image, :slug)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commerce_params
      params.require(:commerce).permit(:first_name, :last_name, :commerce_name, :email, :password, :password_confirmation, :address, :phone_number, :latitude, :longitude, :register_commerce, :logo, :image, :slug)
    end
end

app/controllers/commerces/sessions_controller.rb
# frozen_string_literal: true

class Commerces::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_user, only: :destroy
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/commerces/unlocks_controller.rb
# frozen_string_literal: true

class Commerces::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/commerces_controller.rb
class CommercesController < ApplicationController
	
	def index
		if params[:search].present?
    		@commerces = Commerce.near(params[:search], 2, units: :km)
		else
		    @commerces = Commerce.all
		end
	end

	def show
		@commerce = Commerce.friendly.find(params[:id])
		@products = @commerce.products
		@reviews = Review.where(commerce_id: @commerce.id).order("created_at DESC")
		@review = Review.new
		@commerces = Commerce.all

		if @reviews.blank?
			@avg_review = 0
		else 
			@avg_review = @reviews.average(:rating).round(2)
		end 
	end
end

app/helpers/commerces_helper.rb
module CommercesHelper
end

app/views/commerces/index.html.erb
<% provide(:title, "shops") %>

<section>
    <div class="container">
        <h4 style="color: #3C472F">Trouvez des Shops proche de vous</h4>
        <%= form_tag commerces_path, :method => :get do %>
          <p>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Search Near", :name => nil, class: "green-btn" %>
          </p>
        <% end %>    
    </div>
</section>



<section class="commerce">
  <div class="container">
    <h2>Shops</h2>
      <% @commerces.each_slice(6) do |commerces| %>
        <div class="row">
          <% commerces.each do |commerce| %>  
            <div class="col-md-2 col-sm-2">
              <div class="row">
                <%= link_to commerce do %>
                  <%= image_tag commerce.logo.url(:large), class: "commerce-logo" %>
                  <% if params[:search].present? %>
                    (<%= commerce.distance.round(2) %> km)
                  <% end %>
                <% end %> 
              </div>
            </div>  
          <% end %>
        </div>  
      <% end %>
    </div>
  </div>
</section>

app/views/commerces/show.html.erb
<% provide(:title, "#{@commerce.commerce_name}") %>


<div class="container">
  <div class="row">
    <div class="col-md-8">  
      <div class="commerce-background" style="background: url(<%= @commerce.image.url(:large) %>); border: 1px solid #ccc">
        <%= image_tag @commerce.logo.url(:large), class: "commerce-show-logo" %>
      </div>
      <% if commerce_signed_in? %>
          <%= link_to new_commerce_product_path(@commerce), class: "bt btn-product" do %>
          <%= image_tag "149171.svg", class: "link-svg" %>
            Nouveau produit
          <% end %>
      <% end %>
      <% @products.each do |product| %>   
      <div class="product">
        <div class="row">
          <div class="col-md-2 col-sm-2 col-xs-2">
            <%= image_tag product.image.url(:large), class: "product-image" %>
          </div>
          <div class="col-md-4 col-sm-4 col-xs-4">
            <h3 class="product-title"><%= product.title %></h3>
            <h6>Avant le <%= product.last_date.strftime("%m/%d/%Y à %I:%M%p") %></h6>
          </div>
          <div class="col-md-2 col-sm-2 col-xs-2">
            <% if product.ilimit == true %>
              <h3 class="product-quantity text-center">ilimité</p></h3>
            <% else %>
            <h3 class="product-quantity text-center"><%= product.quantity %><br> <p>Unités</p></h3>
            <% end %>
          </div>
          <div class="col-md-2"></div>
            <div class="col-md-2 col-sm-2 col-xs-2">
              <p class="price">
                <span class="product-price" style="color:#223d61"><s><%= number_to_currency(product.real_price, unit: "") %> DH</s></span>
              </p>
              <p class="price">
                <span class="product-price"><%= number_to_currency(product.price, unit: "") %> DH</span>
              </p>
              <p class="product-discount">- <%= number_to_percentage((product.price * 100) / product.real_price, precision: 0) %></p>
            </div>
          </div>
          <% if current_commerce && @commerce.id == current_commerce.id %>
            <%= link_to 'éditer', edit_commerce_product_path(@commerce, product), class: "edit-btn bt" %>
            <%= link_to "éliminer", commerce_product_path(@commerce, product), method: :delete, data: { confirm: "Are you sure?" }, class: "delete-btn bt" %>
          <% end %>
        </div> 
      <% end %>




      <div id="reviews">
        <h5>Commentaires</h5>
        <% @reviews.each do |review| %>
        <div class="review">
          <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-3">
              <h6 class="review-date"><%= review.created_at.to_date %></h6>
              <p class="review-user"><%= review.user.first_name %></p>
            </div>
            <div class="col-md-9 col-sm-3 col-xs-3">
              <div class="star-rating" data-score= <%= @avg_review %> ></div>
              <em class="review-comment"><%= review.comment %></em>
            </div>
          </div>
          </div>
        <% end %> 
          <h6 class="add-review">
          Ecriver un commentaire</h6>
          
        <%= render "reviews/new" %>
      </div>
<h4>Nearby shops</h4>
<div class="row">
<ul>
  <% for commerce in @commerce.nearbys(4, units: :km) %>
    <div class="col-md-2 col-sm-4 col-xs-4">
      <div class="commerce">
        <%= link_to commerce do %>
          <%= image_tag commerce.logo.url(:large), class: "commerce-logo" %>
        <% end %>
        (<%= commerce.distance.round(2) %> km) 
      </div>
    </div>
  <% end %>
</ul>
</div>

    </div>
    <div class="col-md-4">
      <div id="map"></div>
    <script>
      function initMap() {
        var uluru = {lat: <%= @commerce.latitude %>, lng: <%= @commerce.longitude %> };
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 13,
          center: uluru
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCXYYNHt5bguptWTF27gBIdRe4Vmz05rUw&callback=initMap">
    </script>
    <h5><i class="fa fa-map-marker"></i> <%= @commerce.address %></h5>
    <h5><i class="fa fa-phone"></i> <%= @commerce.phone_number %></h5>

    
</div>
          
  </div>
</div>
</div>

<script>
    $('.star-rating').raty({
      path: '/assets',
      readOnly: true,
      score: function() {
        return $(this).attr('data-score');
      }
    });
</script>