config/routes.rb
Rails.application.routes.draw do
  get 'about/index'

  get 'register/index'
  get 'login/index'
  get 'welcome/index'

  devise_for :commerces, path: 'commerces', controllers: { sessions: 'commerces/sessions', registrations: 'commerces/registrations' } 
  devise_for :users, path: 'users', controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :commerces do 
  	resources :products
    resources :reviews
  end

  resources :products

  root "welcome#index"

  get 'commerces/:id' => 'commerces#show'

  get 'auth/:provider/callback' => 'sessions#create'
  get 'auth/failure' => redirect('/')
  delete 'signout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commerce.rb
class Commerce < ApplicationRecord
  extend FriendlyId
  friendly_id :commerce_name, use: :slugged
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :commerce_name, :address, :phone_number, :logo, presence: true
  has_many :products
  has_many :reviews

  	has_attached_file :logo, styles: { large: "600x600>" }, 
		:path => ":rails_root/public/system/:logo/:id/:style/:filename",
    	:url => "/system/:logo/:id/:style/:filename"
  	validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/

  	has_attached_file :image, styles: { large: "600x600>" }, 
		:path => ":rails_root/public/system/:image/:id/:style/:filename",
    	:url => "/system/:image/:id/:style/:filename"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

    geocoded_by :address
    after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }  
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :commerce

	has_attached_file :image, styles: { large: "600x600>" }, 
		:path => ":rails_root/public/system/:image/:id/:style/:filename",
    	:url => "/system/:image/:id/:style/:filename"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
	belongs_to :commerce
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   validates :first_name, presence: true

   has_many :reviews, dependent: :destroy

   def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.first_name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end 
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_commerce!, only: [:edit, :update, :destroy]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search].present?
        @commerces = Commerce.near(params[:search], 2, units: :km)
    else
        @commerces = Commerce.all
    end
  end 

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to current_commerce }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to current_commerce }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to current_commerce }
    end
  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

    def set_commerce 
      @commerce = Commerce.find(params[:commerce_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :real_price, :last_date, :quantity, :ilimit, :image).merge(commerce_id: current_commerce.id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_commerce
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @commerce, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @commerce, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to @commerce, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_commerce 
      @commerce = Commerce.friendly.find(params[:commerce_id])
    end 
    def set_review
      @review = Review.find(params[:id])
    end

    def review_params
      params.require(:review).permit(:rating, :comment).merge(user_id: current_user.id, commerce_id: @commerce.id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@commerces = Commerce.all.order("created_at DESC")
  	@products = Product.all.order("created_at DESC")
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
		:user && :commerce
	end

	def resource
		@resource ||= User.new && Commerce.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end

	def full_title(page_title= '')
		base_title= "Kusele"
		if page_title.empty?
			base_title
		else
			base_title + " | " + page_title
		end
	end
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/commerces_helper.rb
module CommercesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer-policy">
	<div class="container text-center">
		<p style="font-family: HelveticaRoundedLTStd-Bd">consultez notre politique de confidentialite</h6>
	</div>	
</footer>

app/views/layouts/_header.html.erb
<% unless current_page?(root_path) %>
<header id="main_menu" class="header navbar-fixed">            
    <div class="main_menu_bg">
        <div class="container">
            <div class="row">
                <div class="nave_menu">
                    <nav class="navbar navbar-default" id="navmenu">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <%= link_to root_path, class: "navbar-brand" do %>
                                    <p class="logo-pa"><%= image_tag "logo.png", class: "logo" %>
                                            </p>            
                                <% end %>
                            </div>
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav navbar-left">
                                    <li><%= link_to "Accueil", root_path %></li>
                                    <li><%= link_to "À propos", about_index_path %></li>
                                    <li><%= link_to "Shops", commerces_path %></li>
                                    <li><%= link_to "Annonces", root_path %></li>
                                </ul>
                                <ul class="nav navbar-nav navbar-right">
                                    <% if !commerce_signed_in? && !user_signed_in? %>
                                        <li><%= link_to "s'inscrire", register_index_path %></li>
                                        <li><%= link_to "se connecter", login_index_path %></li>
                                    <% else %>
                                        <% if user_signed_in? %>
                                            <li><%= link_to "edit account", edit_user_registration_path %></li>
                                            <li><%= link_to "se déconnecter", destroy_user_session_path, method: :delete %></li> 
                                        <% end %>
                                        <% if commerce_signed_in? && !user_signed_in? %>
                                            <li><%= link_to "mon shop", commerce_path(current_commerce) %></li>
                                            <li><%= link_to "edit shop", edit_commerce_registration_path %></li>
                                            <li><%= link_to "se déconnecter", destroy_commerce_session_path, method: :delete %></li> 
                                        <% end %>
                                    <% end %>    
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>  
            </div>
        </div>
    </div>
</header> 
<% else %>
<header id="main_menu" class="header navbar-fixed">            
    <div class="main_menu_bg">
        <div class="container">
            <div class="row">
                <div class="nave_menu">
                    <nav class="navbar navbar-default" id="navmenu">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                </button>
                                <%= link_to root_path, class: "navbar-brand" do %>
                                    <p class="logo-pa"><%= image_tag "logo.png", class: "logo" %></p>
                                <% end %>
                            </div>
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav navbar-left">
                                    <li><a href="#android">Acceuil</a></li>
                                    <li><a href="#about">À propos</a></li>
                                    <li><a href="#shop">Shops</a></li>
                                    <li><a href="#home">Annonces</a></li>
                                    <li class="hide"><a href="#service">What we do?</a></li>
                                </ul>
                                <ul class="nav navbar-nav navbar-right">
                                    <% if !commerce_signed_in? && !user_signed_in? %>
                                        <li><%= link_to "s'inscrire", register_index_path %></li>
                                        <li><%= link_to "se connecter", login_index_path %></li>
                                    <% else %>
                                        <% if user_signed_in? %>
                                            <li><%= link_to "edit account", edit_user_registration_path %></li>
                                            <li><%= link_to "se déconnecter", destroy_user_session_path, method: :delete %></li> 
                                        <% end %>
                                        <% if commerce_signed_in? && !user_signed_in? %>
                                            <li><%= link_to "mon shop", commerce_path(current_commerce) %></li>
                                            <li><%= link_to "edit shop", edit_commerce_registration_path %></li>
                                            <li><%= link_to "se déconnecter", destroy_commerce_session_path, method: :delete %></li> 
                                        <% end %>
                                    <% end %>       
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>  
            </div>
        </div>
    </div>
</header> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'logo.png' %>
    <title><%=full_title(yield(:title))%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick.css"/>
   </head>

  <body>
  <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '{2130007637227889}',
      cookie     : true,
      xfbml      : true,
      version    : '{latest-api-version}'
    });
      
    FB.AppEvents.logPageView();   
      
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
  </script>
	<%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>

    <script type="text/javascript" src="//cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick.min.js"></script>
  </body>
</html>